// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// vunirootRcpp
Rcpp::List vunirootRcpp(Rcpp::Function f, Rcpp::NumericVector lower, Rcpp::NumericVector upper, Rcpp::NumericVector fa, Rcpp::NumericVector fb, int numiter, double tol);
RcppExport SEXP _survextrap_vunirootRcpp(SEXP fSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP faSEXP, SEXP fbSEXP, SEXP numiterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fa(faSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type fb(fbSEXP);
    Rcpp::traits::input_parameter< int >::type numiter(numiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(vunirootRcpp(f, lower, upper, fa, fb, numiter, tol));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_stan_fit4survextrap_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_survextrap_vunirootRcpp", (DL_FUNC) &_survextrap_vunirootRcpp, 7},
    {"_rcpp_module_boot_stan_fit4survextrap_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4survextrap_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_survextrap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
