# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vunirootRcpp <- function(f, lower, upper, fa, fb, numiter, tol) {
    .Call(`_survextrap_vunirootRcpp`, f, lower, upper, fa, fb, numiter, tol)
}

